# -*- coding: utf-8 -*-
"""Copy of Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WS31OF1HAKqu0yl8HxfbZIxZ8wQN-mTU
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

ategorical_cols = ['Juja']  # Add other categorical columns if any

data = pd.read_csv('///content/Book 2 Dataset csv.csv')

print(data.head())
print(data.info())
print(data.describe())

data = data.drop('Time', axis=1)

data.fillna(method='ffill', inplace=True)

X = data.drop('Severity', axis=1)
y = data['Severity']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,
random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

